<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Entity\Site;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Type extends \Concrete\Core\Entity\Site\Type implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'siteTypeID', 'siteTypeHandle', 'siteTypeName', 'siteTypeThemeID', 'siteTypeHomePageTemplateID', 'sites', 'package'];
        }

        return ['__isInitialized__', 'siteTypeID', 'siteTypeHandle', 'siteTypeName', 'siteTypeThemeID', 'siteTypeHomePageTemplateID', 'sites', 'package'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Type $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isDefault()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDefault', []);

        return parent::isDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteTypeID()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSiteTypeID();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteTypeID', []);

        return parent::getSiteTypeID();
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteTypeHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteTypeHandle', []);

        return parent::getSiteTypeHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteTypeHandle($siteTypeHandle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteTypeHandle', [$siteTypeHandle]);

        return parent::setSiteTypeHandle($siteTypeHandle);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteTypeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteTypeName', []);

        return parent::getSiteTypeName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteTypeName($siteTypeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteTypeName', [$siteTypeName]);

        return parent::setSiteTypeName($siteTypeName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSites', []);

        return parent::getSites();
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteTypeThemeID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteTypeThemeID', []);

        return parent::getSiteTypeThemeID();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteTypeThemeID($siteTypeThemeID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteTypeThemeID', [$siteTypeThemeID]);

        return parent::setSiteTypeThemeID($siteTypeThemeID);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteTypeHomePageTemplateID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteTypeHomePageTemplateID', []);

        return parent::getSiteTypeHomePageTemplateID();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteTypeHomePageTemplateID($siteTypeHomePageTemplateID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteTypeHomePageTemplateID', [$siteTypeHomePageTemplateID]);

        return parent::setSiteTypeHomePageTemplateID($siteTypeHomePageTemplateID);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackage', []);

        return parent::getPackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackage($package)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackage', [$package]);

        return parent::setPackage($package);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageID', []);

        return parent::getPackageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageHandle', []);

        return parent::getPackageHandle();
    }

}
