<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Entity\Statistics\UsageTracker;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StackUsageRecord extends \Concrete\Core\Entity\Statistics\UsageTracker\StackUsageRecord implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'stack_id', 'block_id', 'collection_id', 'collection_version_id'];
        }

        return ['__isInitialized__', 'stack_id', 'block_id', 'collection_id', 'collection_version_id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StackUsageRecord $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getStackId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStackId', []);

        return parent::getStackId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStackId($stack_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStackId', [$stack_id]);

        return parent::setStackId($stack_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getBlockId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBlockId', []);

        return parent::getBlockId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBlockId($block_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBlockId', [$block_id]);

        return parent::setBlockId($block_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollectionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollectionId', []);

        return parent::getCollectionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollectionId($collection_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollectionId', [$collection_id]);

        return parent::setCollectionId($collection_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollectionVersionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollectionVersionId', []);

        return parent::getCollectionVersionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollectionVersionId($collection_version_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollectionVersionId', [$collection_version_id]);

        return parent::setCollectionVersionId($collection_version_id);
    }

}
