<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Entity\Attribute\Value\Value;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SelectValueOption extends \Concrete\Core\Entity\Attribute\Value\Value\SelectValueOption implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'avSelectOptionID', 'list', 'values', 'isEndUserAdded', 'isDeleted', 'displayOrder', 'value'];
        }

        return ['__isInitialized__', 'avSelectOptionID', 'list', 'values', 'isEndUserAdded', 'isDeleted', 'displayOrder', 'value'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SelectValueOption $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getOptionList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionList', []);

        return parent::getOptionList();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionList($list)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionList', [$list]);

        return parent::setOptionList($list);
    }

    /**
     * {@inheritDoc}
     */
    public function isOptionDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOptionDeleted', []);

        return parent::isOptionDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOptionDeleted($isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOptionDeleted', [$isDeleted]);

        return parent::setIsOptionDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectAttributeOptionID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelectAttributeOptionID', []);

        return parent::getSelectAttributeOptionID();
    }

    /**
     * {@inheritDoc}
     */
    public function setSelectAttributeOptionID($avSelectOptionID)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSelectAttributeOptionID', [$avSelectOptionID]);

        return parent::setSelectAttributeOptionID($avSelectOptionID);
    }

    /**
     * {@inheritDoc}
     */
    public function isEndUserAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEndUserAdded', []);

        return parent::isEndUserAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEndUserAdded($isEndUserAdded)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEndUserAdded', [$isEndUserAdded]);

        return parent::setIsEndUserAdded($isEndUserAdded);
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectAttributeOptionValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelectAttributeOptionValue', []);

        return parent::getSelectAttributeOptionValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setSelectAttributeOptionValue($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSelectAttributeOptionValue', [$value]);

        return parent::setSelectAttributeOptionValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayOrder', []);

        return parent::getDisplayOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayOrder($displayOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayOrder', [$displayOrder]);

        return parent::setDisplayOrder($displayOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getSelectAttributeOptionDisplayValue($format = 'html')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelectAttributeOptionDisplayValue', [$format]);

        return parent::getSelectAttributeOptionDisplayValue($format);
    }

}
