<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Entity\Attribute;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \Concrete\Core\Entity\Attribute\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'akCategoryID', 'akCategoryHandle', 'akCategoryAllowSets', 'types', 'sets', 'keys', 'package'];
        }

        return ['__isInitialized__', 'akCategoryID', 'akCategoryHandle', 'akCategoryAllowSets', 'types', 'sets', 'keys', 'package'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAttributeKeyCategoryID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeKeyCategoryID', []);

        return parent::getAttributeKeyCategoryID();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeKeyCategoryHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeKeyCategoryHandle', []);

        return parent::getAttributeKeyCategoryHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeKeyCategoryHandle($akCategoryHandle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeKeyCategoryHandle', [$akCategoryHandle]);

        return parent::setAttributeKeyCategoryHandle($akCategoryHandle);
    }

    /**
     * {@inheritDoc}
     */
    public function allowAttributeSets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'allowAttributeSets', []);

        return parent::allowAttributeSets();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllowAttributeSets($akCategoryAllowSets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllowAttributeSets', [$akCategoryAllowSets]);

        return parent::setAllowAttributeSets($akCategoryAllowSets);
    }

    /**
     * {@inheritDoc}
     */
    public function getController()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getController', []);

        return parent::getController();
    }

    /**
     * {@inheritDoc}
     */
    public function clearAttributeKeyCategoryTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearAttributeKeyCategoryTypes', []);

        return parent::clearAttributeKeyCategoryTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeKeyCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeKeyCategory', []);

        return parent::getAttributeKeyCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeSets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeSets', []);

        return parent::getAttributeSets();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttributeTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttributeTypes', []);

        return parent::getAttributeTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttributeTypes($types)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttributeTypes', [$types]);

        return parent::setAttributeTypes($types);
    }

    /**
     * {@inheritDoc}
     */
    public function addSet($handle, $name, $pkg = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSet', [$handle, $name, $pkg]);

        return parent::addSet($handle, $name, $pkg);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function associateAttributeKeyType(\Concrete\Core\Entity\Attribute\Type $type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'associateAttributeKeyType', [$type]);

        return parent::associateAttributeKeyType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackage', []);

        return parent::getPackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackage($package)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackage', [$package]);

        return parent::setPackage($package);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageID', []);

        return parent::getPackageID();
    }

    /**
     * {@inheritDoc}
     */
    public function getPackageHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackageHandle', []);

        return parent::getPackageHandle();
    }

}
