<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Geolocator extends \Concrete\Core\Entity\Geolocator implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'glID', 'glHandle', 'glName', 'glDescription', 'glConfiguration', 'glPackage', 'glActive'];
        }

        return ['__isInitialized__', 'glID', 'glHandle', 'glName', 'glDescription', 'glConfiguration', 'glPackage', 'glActive'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Geolocator $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getGeolocatorID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeolocatorID', []);

        return parent::getGeolocatorID();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeolocatorHandle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeolocatorHandle', []);

        return parent::getGeolocatorHandle();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeolocatorHandle($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeolocatorHandle', [$value]);

        return parent::setGeolocatorHandle($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeolocatorName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeolocatorName', []);

        return parent::getGeolocatorName();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeolocatorDisplayName($format = 'html')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeolocatorDisplayName', [$format]);

        return parent::getGeolocatorDisplayName($format);
    }

    /**
     * {@inheritDoc}
     */
    public function setGeolocatorName($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeolocatorName', [$value]);

        return parent::setGeolocatorName($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeolocatorDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeolocatorDescription', []);

        return parent::getGeolocatorDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getGeolocatorDisplayDescription($format = 'html')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeolocatorDisplayDescription', [$format]);

        return parent::getGeolocatorDisplayDescription($format);
    }

    /**
     * {@inheritDoc}
     */
    public function setGeolocatorDescription($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeolocatorDescription', [$value]);

        return parent::setGeolocatorDescription($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeolocatorConfiguration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeolocatorConfiguration', []);

        return parent::getGeolocatorConfiguration();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeolocatorConfiguration(array $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeolocatorConfiguration', [$value]);

        return parent::setGeolocatorConfiguration($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeolocatorPackage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeolocatorPackage', []);

        return parent::getGeolocatorPackage();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeolocatorPackage(\Concrete\Core\Entity\Package $value = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeolocatorPackage', [$value]);

        return parent::setGeolocatorPackage($value);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$value]);

        return parent::setIsActive($value);
    }

}
