<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-11-23T10:13:16+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.4',
    'version_db_installed' => '20200609145307',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1637557066,
        'do_page_reindex_check' => true,
        'latest_version' => '8.5.4',
    ],
    'calendar' => [
        'topic_attribute' => 'event_categories',
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'custom',
        'full_page_lifetime_value' => '2',
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
];
