<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-11-22T05:40:59+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'c5 Test',
        ],
    ],
];
